version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13 
  build:
    commands:
      - go build main.go
  post_build:
    commands:
      - zip function.zip main esyhealth-pdf.html    
artifacts:
  files:
    - function.zip
